FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /src
COPY pom.xml .
COPY src src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /src/target/payflow-gateway.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
