package com.payflow.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHENTICATED,
    TOKEN_EXPIRED,
    FORBIDDEN,
    NOT_FOUND,
    IDEMPOTENCY_IN_PROGRESS,
    IDEMPOTENCY_KEY_REUSED,
    INSUFFICIENT_BALANCE,
    ACCOUNT_INACTIVE,
    SELF_TRANSFER,
    LIMIT_EXCEEDED,
    WALLET_LOCKED,
    PIN_REQUIRED,
    PIN_INVALID,
    TWO_FACTOR_REQUIRED,
    ALREADY_REFUNDED,
    ALREADY_PAID,
    RATE_LIMITED,
    GATEWAY_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    LOCK_TIMEOUT,
    INTERNAL_ERROR
}
