spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

management:
  health:
    rabbit:
      enabled: ${MANAGEMENT_HEALTH_RABBIT_ENABLED:false}
